stages:
  - test
  - build
  - deploy

variables:
  JAVA_VERSION: "21"
  MAVEN_OPTS: "-Xmx2048m"

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn test
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/surefire-reports/
    expire_in: 1 week

build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - echo "Deploy to production"
  only:
    - main
