version: '3.8'

services:
  # Main basket pricing service only
  basket-pricing-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: basket-pricing-service:latest  # Tag the built image
    container_name: basket-pricing-service
    pull_policy: build  # Always build, never pull
    ports:
      - "8080:8080"   # REST API
      - "9090:9090"   # gRPC
      - "8081:8081"   # Actuator/Management
    environment:
      # Spring profiles
      - SPRING_PROFILES_ACTIVE=default
      
      # Application settings
      - SERVER_PORT=8080
      - MANAGEMENT_SERVER_PORT=8081
      - GRPC_SERVER_PORT=9090
      
      # Refinitiv configuration (override with your credentials)
      - REFINITIV_HOST=${REFINITIV_HOST:-ads1}
      - REFINITIV_PORT=${REFINITIV_PORT:-14002}
      - REFINITIV_SERVICE_NAME=${REFINITIV_SERVICE_NAME:-ELEKTRON_DD}
      - REFINITIV_USERNAME=${REFINITIV_USERNAME:-user1}
      
      # Logging
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_SRVISWAN=DEBUG
      
      # JVM options
      - JAVA_OPTS=-Xmx2g -Xms1g
      
    volumes:
      # Mount logs directory
      - ./logs:/app/logs
      
    networks:
      - basket-pricing-network
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: basket-pricing-prometheus
    pull_policy: missing  # Only pull if not available locally
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus-minimal.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - basket-pricing-network
    restart: unless-stopped

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: basket-pricing-grafana
    pull_policy: missing  # Only pull if not available locally
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    networks:
      - basket-pricing-network
    restart: unless-stopped

networks:
  basket-pricing-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:

