server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

refinitiv:
  host: ${REFINITIV_HOST:}
  port: ${REFINITIV_PORT:14002}
  user: ${REFINITIV_USER:}
  service: ${REFINITIV_SERVICE:ELEKTRON_DD}

logging:
  level:
    com.srviswan.basketpricing: INFO
    com.refinitiv: WARN


